server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 根据 Eureka 服务名自动转发
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0 # 保留 /auth 前缀
        - id: file-service
          uri: lb://auth-service
          predicates:
            - Path=/files/**
          filters:
            - StripPrefix=0 # 保留 /files 前缀，转发到auth-service的FileController
        - id: org-service
          uri: lb://org-service
          predicates:
            - Path=/org/**
          filters:
            - StripPrefix=0 # 保留 /org 前缀
        - id: pet-service
          uri: lb://pet-service
          predicates:
            - Path=/pets/**
          filters:
            - StripPrefix=0 # 保留 /pets 前缀
        - id: interview-service
          uri: lb://interview-service
          predicates:
            - Path=/interview/**
          filters:
            - StripPrefix=0 # 保留 /interview 前缀
        - id: adoption-service
          uri: lb://adoption-service
          predicates:
            - Path=/adoptions/**
          filters:
            - StripPrefix=0 # 保留 /adoptions 前缀
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=0 # 保留 /notification 前缀
